services:
  notebook:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]
