services:
  notebook:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - data:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]
